version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /ci/markdownlint
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /adapters/node
    schedule:
      interval: weekly
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: maven
    directory: /adapters/java
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /adapters/go
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /ci/go-tools
    schedule:
      interval: weekly
