apiVersion: 1
prune: true
datasources:
  - name: otelc Prometheus
    uid: otelc-prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
