[package]
name = "quux-otelc-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
[[bin]]
name = "quux-otelc"
path = "src/main.rs"
[dependencies]
anyhow.workspace = true
serde_json.workspace = true
quux-otelc-config = { path = "../config" }
quux-otelc-symbols = { path = "../symbols" }
shell-words = "1.1"
tempfile = "3"

[dev-dependencies]
tempfile = "3"
prost.workspace = true
opentelemetry-proto.workspace = true
