[package]
name = "quux-otelc-export"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
[dependencies]
anyhow.workspace = true
prost.workspace = true
opentelemetry-proto.workspace = true
ureq.workspace = true
quux-otelc-config = { path = "../config" }
httpdate = "1"
opentelemetry.workspace = true
opentelemetry_sdk.workspace = true
serde_json.workspace = true
